# SAM deployment template
# Docs at: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#resource-types

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for Lipwig

Globals:
  Function:
    Runtime: python3.7
    CodeUri: app/
    Timeout: 5  # Allow time for posting to external services
    Environment:
      Variables:
        LOG_LEVEL: INFO

Resources:

  LipwigFunctionExecRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: 2012-10-17
      Policies:
        - PolicyName: 'LipwigFunctionExecRolePolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 'kms:Decrypt'
                Resource: !Sub 'arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/*'
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
              - Effect: Allow
                Action: 'sns:Subscribe'
                Resource: !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:*'
              - Effect: Allow
                Action: 'ssm:DescribeParameters'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'ssm:GetParameter'
                  - 'ssm:GetParameters'
                Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/Lipwig/*'

  CloudWatchLogsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: 'Logs SNS events to CloudWatch.'
      Handler: lipwig.cloud_watch_logs.lambda_handler
      Role: !GetAtt LipwigFunctionExecRole.Arn

  SlackFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: 'Posts SNS events to Slack.'
      Handler: lipwig.slack.lambda_handler
      Role: !GetAtt LipwigFunctionExecRole.Arn


# Make Lipwig functions accessible to other stacks
Outputs:

  CloudWatchLogsFunction:
    Description: 'Logs SNS events to CloudWatch.'
    Value: !GetAtt CloudWatchLogsFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-CloudWatchLogsFunction'

  SlackFunction:
    Description: 'Posts SNS events to Slack.'
    Value: !GetAtt SlackFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-SlackFunction'
